# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-25 06:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dailypost', '0002_auto_20170825_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailypost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
