# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-28 16:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailypost', '0003_auto_20170825_1414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '文章分类', 'verbose_name_plural': '文章分类'},
        ),
        migrations.AlterModelOptions(
            name='dailypost',
            options={'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
    ]
