# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailypost', '0005_auto_20170828_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailypost',
            name='size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
