# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 10:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailypost', '0006_dailypost_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailypost',
            old_name='size',
            new_name='pic_size',
        ),
    ]
