# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 10:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailypost', '0007_auto_20170906_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailypost',
            name='pic_size',
        ),
    ]
