# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailypost', '0008_remove_dailypost_pic_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiddenPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_time', models.DateField()),
                ('body', models.TextField()),
                ('excerpt', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('category', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
    ]
