# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailypost', '0009_hiddenpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hiddenpost',
            options={'verbose_name': '隐藏文章', 'verbose_name_plural': '隐藏文章'},
        ),
    ]
