# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-26 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0003_auto_20170826_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='pics',
            name='date',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pics',
            name='hidden',
            field=models.IntegerField(default=0),
        ),
    ]
