# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-28 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0004_auto_20170826_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='pics',
            name='pic_index',
            field=models.IntegerField(default=0),
        ),
    ]
