# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-28 10:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0005_pics_pic_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pics',
            old_name='pic_index',
            new_name='index',
        ),
    ]
