# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-28 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0006_auto_20170828_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pics',
            name='date',
        ),
        migrations.AlterField(
            model_name='pics',
            name='created_time',
            field=models.DateField(),
        ),
    ]
