# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-28 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0007_auto_20170828_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pics',
            name='index',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
