# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-28 11:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0008_auto_20170828_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pics',
            old_name='index',
            new_name='pic_index',
        ),
    ]
