# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-29 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0009_auto_20170828_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='pics',
            name='tags',
            field=models.ManyToManyField(blank=True, to='pics.Tags'),
        ),
    ]
