# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-31 09:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0011_auto_20170830_0925'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FuLi',
        ),
    ]
