# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0012_delete_fuli'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pics',
            name='pic_index',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
