# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0013_auto_20170831_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pics',
            name='hidden',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='pics',
            name='likes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='pics',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pics',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
