# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0014_auto_20170906_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='pics',
            name='pic_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
