# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0015_pics_pic_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pics',
            name='likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
