# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0016_auto_20170906_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pics',
            name='likes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='pics',
            name='pic_size',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
