# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0017_auto_20170906_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='pics',
            name='hashcode',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
